### ISSUE TITLE
pycaw ownership on PyPI

### ISSUE THREAD

**Issue by AndreMiras** [Jailibrary/PyCaw#1]
Hi :wave: 

I'm the developer of https://github.com/AndreMiras/pycaw
I was [eventually about to publish the package on PyPI](https://github.com/AndreMiras/pycaw/issues/6) and noticed you very recently got the ownership via https://github.com/Jailibrary/PyCaw :cry: 
Would you agree to transfer ownership to me?
As a compensation I'm willing to buy it, contribute to some of your repos or anything that seems reasonable to both of us.
My library already has few people referencing it [here](https://stackoverflow.com/search?q=pycaw) and [there](https://duckduckgo.com/?q=pycaw+windows+audio&ia=software).
And its initial commit 3 years ago:
https://github.com/AndreMiras/pycaw/commit/231341005d81b20d8adbecb2348e8eeaa26f3c63

I tried reaching out to you via email, but it bounced back.
I understand this is a rather weird and annoying request, but I have to ask.
I hope you understand and you don't mind too much.

Best regards,

**Comment by Jailibrary** [comment]
Hi, sorry for the late response. You can email me at oliverxur@gmail.com.

Thanks!

**Comment by AndreMiras** [comment]
I confirmed this was transferred over, thanks for your cooperation :+1:
